name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install wait-on
        run: npm install -g wait-on
      - name: Start server for E2E testing
        run: CLIENT_ID="${{ secrets.CLIENT_ID }}" REDIRECT_URI="${{ secrets.REDIRECT_URI }}" CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}" npm start & npx wait-on -t 10000 http://localhost:8080
      - name: Run E2E tests
        run: npm run cy:test --  --env idpUsername="${{ secrets.IDP_USERNAME }}",idpPassword="${{ secrets.IDP_PASSWORD }}"
